### ISSUE TITLE
Remove sensitive credential files

### ISSUE THREAD

**Issue by andreas-bauer** [akashmernedi/d-vibe#1]
@akashMernedi @gaurisingh21  please delete `android/app/google-services.json`.  
Credential files should never be commited into the repository. 

Have a look at [GitHub's docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) to see how you can delete in in a proper way from your repository.

**Comment by akashmernedi** [comment]
Thank you for flagging the error @andreas-bauer. All the changes are done and I am closing the error.
